version: '3'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'symptom_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'rootroot'
      MYSQL_ROOT_PASSWORD: 'rootroot'
    ports:
      - 3306:3306
      - 33060:33060
    working_dir: /var/lib/mysql
    volumes:
        - "./mysql:/var/lib/mysql:rw"
  backend:
    build: ./backend
    ports:
      - 5000:5000
    restart: always
    depends_on:
      - db